### ISSUE TITLE
Coming soon CTA Button 

### ISSUE THREAD

**Issue by dewank07** [ElixirTechCommunity/Nexus_Website#26]
**Recreate 2nd button from right first row**
https://codepen.io/yuhomyan/pen/OJMejWJ
![image](https://user-images.githubusercontent.com/68022840/185576760-6025d2e9-81ff-4593-a25e-f22ad8c03260.png)

**colour** 
*copy paste the given CSS.*
background-image: linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%);

**Comment by pulkit-30** [comment]
completed #61
