### ISSUE TITLE
Update the glassmorphism carousels

### ISSUE THREAD

**Issue by dewank07** [ElixirTechCommunity/Nexus_Website#27]
**Make the glass effect like this for carousels**
https://codepen.io/opeala/pen/yLaMBvN
![image](https://user-images.githubusercontent.com/68022840/185585756-767cf9f4-e9e0-44ca-90dc-4c337fe7a4cb.png)

**Comment by Anv3sh** [comment]
The basic `tilt effect` is implemented in #34 all that remains is the `glare effect` we might keep this issue open for now for that to be implemented later on.

**Comment by pulkit-30** [comment]
implemented 🚀
