### ISSUE TITLE
Scroll Anchor Tag not functioning as expected.

### ISSUE THREAD

**Issue by SirAbhi13** [ElixirTechCommunity/Nexus_Website#30]
**Describe the bug**
The Scroll button should disappear after being clicked (visible in about and sponsor slides in the background) and the animation for scroll behaviour when clicked should be smooth.

**Expected behavior**
+ Scrolling should be smooth.
+ Scroll button should disappear after being clicked.

https://user-images.githubusercontent.com/72503824/185612339-5d3da758-c98e-43c5-92fb-acf1895e3386.mp4

**Comment by pulkit-30** [comment]
Fixes:

> Scrolling should be smooth.

in styles.css file, define scroll-behavior in `body` tag as smooth
```
body {
.
.
scroll-behavior: smooth;
.
.
}

```

> Scroll button should disappear after being clicked.

try to style the scroll button with position relative rather than absolute and then adjust it from right and left 🚀 

ref: https://github.com/ElixirTechCommunity/Nexus_Website/blob/master/stylesheets/slide_page.css#L26
