### ISSUE TITLE
Landing page elements go over navbar when page is scrolled

### ISSUE THREAD

**Issue by SirAbhi13** [ElixirTechCommunity/Nexus_Website#43]
**Describe the bug**
When you scroll the page from the landing page, the elements (NEXUS, coming soon, the svg) go over the navbar.

**To Reproduce**
Scroll the page slowly

**Expected behavior**
The elements should go behind the navbar when the landing page is scrolled.

**Video**

https://user-images.githubusercontent.com/72503824/185752137-fae11086-4256-49c1-a026-df7363558a4e.mp4

**Comment by dewank07** [comment]
This bug is already solved in #37 either revert back the changes there or merge that PR first.

**Comment by Anv3sh** [comment]
> This bug is already solved in #37 either revert back the changes there or merge that PR first.

Got it 👍🏻
