### ISSUE TITLE
Fix the theme page 

### ISSUE THREAD

**Issue by dewank07** [ElixirTechCommunity/Nexus_Website#56]
**fix the size of theme page tiles**
![image](https://user-images.githubusercontent.com/68022840/185970164-0cede1b3-baeb-490d-823f-b7831f77df80.png)
lower down the size of whole container, so that navigation button don't get overlapped.

**Comment by RamGoel** [comment]
@dewank07 is anyone working on it. Can I start on this.

**Comment by dewank07** [comment]
you can work, I'm assigning you this.

**Comment by pulkit-30** [comment]
fixed
