### ISSUE TITLE
Improve logo design

### ISSUE THREAD

**Issue by pulkit-30** [ElixirTechCommunity/Nexus_Website#8]
### current

<img width="171" alt="Screenshot 2022-08-12 at 12 23 51 PM" src="https://user-images.githubusercontent.com/76155456/184300595-ab1fa11e-2e4b-4f4b-89a3-d08fb82ec4db.png">

### Expected:

<img width="693" alt="Screenshot 2022-08-12 at 12 23 02 PM" src="https://user-images.githubusercontent.com/76155456/184300461-f16d0804-9f11-44d7-972a-86bf77387a46.png">

**Comment by darshikaguptaa** [comment]
Submitted a patch #9
